### ISSUE TITLE
程序运行速度的问题

### ISSUE THREAD

**Issue by jinglou** [yulu0724/ColorNamesExtension#1]
余博士，您好，很冒昧打扰您。

我近日在使用您这篇论文的代码做实验，但发现程序运行速度很慢。
针对每幅图像，我需要得到每个颜色名的概率图，所以将39个颜色名通道分别取出存盘。
但每幅图像大致需要运行17分钟。

代码如下：
`

for cn = 1:length(selected_ex)
	out_ex = im2cLAB2_test(double(img), w2c_ex, cn, selected_ex);
	imwrite(out_ex, 。。。);
end

`

不知道这是不是正常的，还是哪里弄错了，非常期待您的答复，万分感谢。

**Comment by yulu0724** [comment]
不好意思才看到你提的的问题，不知道问题解决没有。在我的电脑上处理速度是很快的。 im2cLAB2_test测试的结果也是很快的，你可以换台电脑试一下。
