### ISSUE TITLE
关于mapping matrix如何得到的问题

### ISSUE THREAD

**Issue by jizhihang** [yulu0724/ColorNamesExtension#2]
你好，咱们的算法中，最终那个mapping matrix是如何训练得到的？一直在用Joost的那个pLSA的结果，而那个文件中的maping matrix是如何训练得到的？方便透露一下吗？

**Comment by yulu0724** [comment]
很抱歉这么晚才看到问题，Joost的PLSA模型是针对基本11 种颜色名称得到的mapping matrix， 我的39种颜色名称训练过程中由于并不是都相互独立，所以原始的PLSA不适用，文章中有说明是如何改进的，你可以参照一下文章，操作起来也比较容易，根据新的PLSA对任意种颜色训练就可以得到相应的mapping matrix了
