### ISSUE TITLE
Proper-Hexa code of 28 color names

### ISSUE THREAD

**Issue by gr8Adakron** [yulu0724/ColorNamesExtension#3]
Hey, I have gone through your paper, it was quite impressive. Thanks for such a curious job. 
I am trying to create the mapping for all the 16 million color hex-code, by stretching these 28 color names. It is like predefined cluster mapping and it saves the time of clustering process at the end of the algorithm.
How can I get the exact hexadecimal code for your designed scale of 28 color-names?

**Comment by gr8Adakron** [comment]
@yulu0724

**Comment by yulu0724** [comment]
> Hey, I have gone through your paper, it was quite impressive. Thanks for such a curious job.
> I am trying to create the mapping for all the 16 million color hex-code, by stretching these 28 color names. It is like predefined cluster mapping and it saves the time of clustering process at the end of the algorithm.
> How can I get the exact hexadecimal code for your designed scale of 28 color-names?

Sorry, the code is not public yet.
